version: '3.8'
services:
  user-service:
    build:
      context: .
      dockerfile: ./services/users/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - kafka
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/user_db

  product-service:
    build:
      context: .
      dockerfile: ./services/product/Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db
      - kafka
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/product_db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_LOGIN_BANNER: "\"You are accessing a private system.\""
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "10"
      PGADMIN_CONFIG_CSFR_ENABLED: "False"
    ports:
      - "5050:80"
    depends_on:
      - db
    command: /bin/sh -c "env && run_pgadmin.py"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
